eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9996/eureka/
server:
  port: 9000
  servlet:
    context-path: /personInfo
spring:
  application:
    name: personal-information
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/csi?characterEncoding=UTF8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /templates
      suffix: .html
  http:
    encoding:
      charset: UTF-8
      enabled: true
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.yaoxx.business.student.entity